name: CI

on:
  pull_request:
      branches:
        - main
        - sarah-blazic-patch-1
  push:
    branches:
      - main
      - sarah-blazic-patch-1
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
